### ISSUE TITLE
Bug with gffread when converting gff3 to gtf (cufflinks 2.2.1)

### ISSUE THREAD

**Issue by Michael31416** [cole-trapnell-lab/cufflinks#79]
How to reproduce:
1. Download ftp://ftp.ensemblgenomes.org/pub/release-34/fungi/gff3/aspergillus_fumigatus/Aspergillus_fumigatus.CADRE.34.gff3.gz
2. Run
   `gffread  Aspergillus_fumigatus.CADRE.34.gff3  -T -o A.gtf`
3. Look for gene 'CADAFUAG00003226' in gff3 file
`grep -e "CADAFUAG00003226" Aspergillus_fumigatus.CADRE.34.gff3`
```
VIII	JCVI	pseudogene	1378345	1379871	.	+	.	ID=gene:CADAFUAG00003226;Name=AFUA_8G05800;biotype=pseudogene;gene_id=CADAFUAG00003226;logic_name=jcvi_fumigatus
VIII	JCVI	pseudogene	1378345	1379871	.	+	.	ID=transcript:CADAFUAT00003226;Parent=gene:CADAFUAG00003226;Name=AFUA_8G05800;biotype=pseudogene;transcript_id=CADAFUAT00003226
```
4. Look for the same gene in A.gtf
`grep -e "CADAFUAG00003226" A.gtf`
(Nothing found).
5. If we check the corresponding  transcript id in A.gtf:
`grep -e "CADAFUAT00003226" A.gtf`

```
VIII	JCVI	exon	1378345	1379871	.	+	.	transcript_id "transcript:CADAFUAT00003226"; gene_id "transcript:CADAFUAT00003226"; gene_name "AFUA_8G05800";
```

**Comment by gpertea** [comment]
So the bug here is about losing the gene_id, right? 
This happens because the parser was essentially lied to about the feature type of that transcript record there as being a  `pseudogene` (so, a "gene" type) instead of `transcript` or `miscRNA` or `pseudoRNA` or anything else that would denote an actual transcript feature type instead of a `gene` feature..

I wonder why they haven't assigned the "pseudogene" feature type to the exon line there as well, just to make sure that the whole hierarchy is "labeled" accordingly as a "pseudogene" (sarcasm, of course).

In order to speed-up the parsing of the gene->transcripts->exons hierarchies the parser currently tries to "guess" the feature level from the feature type..  I think that the GFF format is not strict and standardized enough when it comes to feature types and essential attribute names and values etc. There must be some common sense agreement that the feature type names should match their place in the gene->transcripts->exons hierarchy (i.e. don't call a transcript "gene"). By not following these basic naming conventions all sorts of problems might ensue -- especially for applications which need a rigorous way of recognizing transcript features and discard any non-transcript ones.

**Comment by Michael31416** [comment]
I see... So it is not a bug, really. I found a workaround using `sed` before `gffread`:
```
sed '/transcript_id=/s/pseudogene/transcript/' InputFile.gff3 > Preprocessed.gff3
```
It seems this issue could be closed now.
